# Publish all joint states.
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Trajectory controller.
puma560_jtc:
  type: effort_controllers/JointTrajectoryController
  joints:
      - j1
      - j2
      - j3
      - j4
      - j5
  constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.5
  stop_trajectory_duration: 1.0
  state_publish_rate:  25
  action_monitor_rate: 25
  gains:
      j1: {p: 150.0, i: 0.0, d: 15.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
      j2: {p: 1300.0, i: 0.0, d: 500.0, i_clamp_min: -5.0, i_clamp_max: 5.0}
      j3: {p: 450.0, i: 0.0, d: 220.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
      j4: {p: 0.4, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
      j5: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

# Position Controllers.
j1_pc:
  type: effort_controllers/JointPositionController
  joint: j1
  pid: {p: 150.0, i: 0.0, d: 15.0}

j2_pc:
  type: effort_controllers/JointPositionController
  joint: j2
  pid: {p: 1300.0, i: 0.0, d: 500.0}

j3_pc:
  type: effort_controllers/JointPositionController
  joint: j3
  pid: {p: 450.0, i: 0.0, d: 220.0}

j4_pc:
  type: effort_controllers/JointPositionController
  joint: j4
  pid: {p: 0.4, i: 0.0, d: 0.0}

j5_pc:
  type: effort_controllers/JointPositionController
  joint: j5
  pid: {p: 0.0, i: 0.0, d: 0.0}